# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zd < Formula
  desc "Zendesk CLI — manage tickets, users, and more from the terminal"
  homepage "https://github.com/jaiganneshskytap/Zendesk-CLI"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.1/zd_0.0.1_darwin_amd64.tar.gz"
      sha256 "e8728b5a9d73ef3763acc98171ba83de6682769f197427310b01b27c22ad96c9"

      define_method(:install) do
        bin.install "zd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.1/zd_0.0.1_darwin_arm64.tar.gz"
      sha256 "e1ef2036aaf9cedf9c3fe3cc43f54ae0aa2beafc24476428110c75f2a57baf64"

      define_method(:install) do
        bin.install "zd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.1/zd_0.0.1_linux_amd64.tar.gz"
      sha256 "60dcf56034bf0a3dca860c81ac47de08e90b51426701d1f3c2378b008bc8427a"
      define_method(:install) do
        bin.install "zd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.1/zd_0.0.1_linux_arm64.tar.gz"
      sha256 "d6ca9f01added1ad6886233b333ee83d64c23042fc139b22f6db3ff0bba7b797"
      define_method(:install) do
        bin.install "zd"
      end
    end
  end
end
