# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zd < Formula
  desc "Zendesk CLI — manage tickets, users, and more from the terminal"
  homepage "https://github.com/jaiganneshskytap/Zendesk-CLI"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.2/zd_0.0.2_darwin_amd64.tar.gz"
      sha256 "cb6007d21277f7bd36c62785bed68ca3b3e4782cfdd11a79836674b7d2ba7528"

      define_method(:install) do
        bin.install "zd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.2/zd_0.0.2_darwin_arm64.tar.gz"
      sha256 "ebd8131ae8c5011579072bb40cb7c5e8cd2f46e3595397d78f337eb3270be3c4"

      define_method(:install) do
        bin.install "zd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.2/zd_0.0.2_linux_amd64.tar.gz"
      sha256 "bff28d3e1b8cd120aaaa5f04787aaf89db4e33085d1e6eb3a36b8213e788c8ab"
      define_method(:install) do
        bin.install "zd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jaiganneshskytap/Zendesk-CLI/releases/download/v0.0.2/zd_0.0.2_linux_arm64.tar.gz"
      sha256 "f3b9cf39b0e005e9a676767eaa52c0c3a85bffc8a2a8d2f61bd9efd4cfbe4849"
      define_method(:install) do
        bin.install "zd"
      end
    end
  end
end
